// Autogenerated from Pigeon (v27.3.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum ProximityReaderApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class ProximityReaderApiPigeonCodecReader: FlutterStandardReader {
}

private class ProximityReaderApiPigeonCodecWriter: FlutterStandardWriter {
}

private class ProximityReaderApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return ProximityReaderApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return ProximityReaderApiPigeonCodecWriter(data: data)
  }
}

class ProximityReaderApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = ProximityReaderApiPigeonCodec(readerWriter: ProximityReaderApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ProximityReaderPlatformApi {
  func isAccountLinked(token: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func linkAccount(token: String, completion: @escaping (Result<Void, Error>) -> Void)
  func presentHowToTap(completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ProximityReaderPlatformApiSetup {
  static var codec: FlutterStandardMessageCodec { ProximityReaderApiPigeonCodec.shared }
  /// Sets up an instance of `ProximityReaderPlatformApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ProximityReaderPlatformApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let isAccountLinkedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mek_stripe_terminal.ProximityReaderPlatformApi.isAccountLinked\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isAccountLinkedChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let tokenArg = args[0] as! String
        api.isAccountLinked(token: tokenArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      isAccountLinkedChannel.setMessageHandler(nil)
    }
    let linkAccountChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mek_stripe_terminal.ProximityReaderPlatformApi.linkAccount\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      linkAccountChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let tokenArg = args[0] as! String
        api.linkAccount(token: tokenArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      linkAccountChannel.setMessageHandler(nil)
    }
    let presentHowToTapChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mek_stripe_terminal.ProximityReaderPlatformApi.presentHowToTap\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      presentHowToTapChannel.setMessageHandler { _, reply in
        api.presentHowToTap { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      presentHowToTapChannel.setMessageHandler(nil)
    }
  }
}
