targets:
  $default:
    sources:
      exclude:
        - 'example/**'
        - 'test/**'
    builders:
      source_gen:combining_builder:
        generate_for:
          - 'lib/**/models/*.dart'

      mek_data_class_generator:
        generate_for:
          - 'lib/**/models/*.dart'
