import 'card_api.dart';
import 'charge.dart';
import 'payment_method.dart';
import 'tip.dart';

/// A [PaymentIntentApi] tracks the process of collecting a payment from your customer. We recommend
/// that you create exactly one [PaymentIntentApi] for each order or customer session in your system.
/// You can reference the [PaymentIntentApi] later to see the history of payment attempts for a particular session.
///
/// A [PaymentIntentApi] transitions through multiple statuses throughout its lifetime and ultimately
/// creates at most one successful charge.
class PaymentIntentApi {
  /// The unique identifier for the intent.
  ///
  /// If the intent was created offline the [id] will be nil. See offlineDetails.stripeId for a
  /// unique ID to use while offline.
  /// After the payment has been forwarded the intent’s [id] will be filled in.
  final String id;

  /// When the intent was created.
  /// [DateTime.millisecondsSinceEpoch]
  final int createdInMilliseconds;

  /// The status of the PaymentIntent.
  final PaymentIntentStatusApi status;

  /// The amount to be collected by this [PaymentIntentApi], provided in the currency’s smallest unit.
  final double amount;

  /// Controls when the funds will be captured from the customer’s account.
  final CaptureMethodApi captureMethod;

  /// The currency of the payment.
  final String currency;

  /// Set of key-value pairs attached to the object.
  final Map<String, String> metadata;

  /// Charges that were created by this PaymentIntent, if any.
  final List<ChargeApi> charges;

  /// The payment method to be used in this PaymentIntent. Only valid in the intent returned during
  /// processPaymentIntent when updatePaymentIntent is enabled.
  final PaymentMethodApi? paymentMethod;

  /// ID of the payment method used in this PaymentIntent.
  final String? paymentMethodId;

  /// Details about items included in the amount after confirmation.
  final AmountDetailsApi? amountDetails;

  /// Indicates how much the user intends to tip in addition to the amount by at confirmation time.
  /// This is only non-null in the [PaymentIntentApi] instance returned during collect when using
  /// updatePaymentIntent set to true in processPaymentIntent.
  ///
  /// After [Terminal.processPaymentIntent] the amount will have this tip amount added
  /// to it and the [amountDetails] will contain the breakdown of how much of the amount was a tip.
  final double? amountTip;

  /// Extra information about a [PaymentIntentApi]. This will appear on your customer’s statement
  /// when this [PaymentIntentApi] succeeds in creating a charge.
  final String? statementDescriptor;

  /// Extra dynamic information about a [PaymentIntentApi]. This will appear concatenated with the
  /// [statementDescriptor] on your customer’s statement when this [PaymentIntentApi] succeeds in creating a charge.
  final String? statementDescriptorSuffix;

  // !!! ONLY ON ANDROID !!!

  /// Amount that can be captured from this [PaymentIntentApi].
  final double? amountCapturable;

  /// Amount that was collected by this [PaymentIntentApi].
  final double? amountReceived;

  /// ID of the Connect application that created the [PaymentIntentApi].
  final String? applicationId;

  /// The amount of the application fee for this [PaymentIntentApi].
  final double? applicationFeeAmount;

  /// Reason for cancellation of this [PaymentIntentApi], either user-provided (duplicate, fraudulent,
  /// requested_by_customer, or abandoned) or generated by Stripe internally (failed_invoice,
  /// void_invoice, or automatic).
  final String? cancellationReason;

  /// Populated when status is [PaymentIntentStatusApi.canceled], this is the time at which
  /// the [PaymentIntentApi] was canceled.
  /// [DateTime.millisecondsSinceEpoch]
  final int? canceledAt;

  /// Get the client secret returned by this intent.
  final String? clientSecret;

  /// One of automatic (default) or manual. When the confirmation method is automatic, a [PaymentIntentApi]
  /// can be confirmed using a publishable key. After next_actions are handled, no additional confirmation
  /// is required to complete the payment.
  final ConfirmationMethodApi? confirmationMethod;

  /// ID of the Customer this PaymentIntent belongs to, if one exists. If present, payment methods
  /// used with this [PaymentIntentApi] can only be attached to this Customer, and payment methods
  /// attached to other Customers cannot be used with this [PaymentIntentApi].
  final String? customerId;

  /// An arbitrary string attached to the [PaymentIntentApi]. Often useful for displaying to users.
  final String? descriptionX;

  /// ID of the invoice that created this PaymentIntent, if it exists.
  final String? invoiceId;

  /// Return the account that the PaymentIntent is on behalf of
  final String? onBehalfOf;

  /// ID of the review associated with this PaymentIntent, if any.
  final String? reviewId;

  /// Email address that the receipt for the resulting payment will be sent to.
  final String? receiptEmail;

  /// Value of setup_future_usage associated with this [PaymentIntentApi], if any.
  final PaymentIntentUsageApi? setupFutureUsage;

  /// Get the transfer group of this PaymentIntent
  final String? transferGroup;

  const PaymentIntentApi({
    required this.id,
    required this.amount,
    required this.amountCapturable,
    required this.amountReceived,
    required this.createdInMilliseconds,
    required this.status,
    required this.applicationFeeAmount,
    required this.amountTip,
    required this.statementDescriptor,
    required this.statementDescriptorSuffix,
    this.metadata = const {},
    required this.charges,
    required this.paymentMethod,
    required this.amountDetails,
    required this.applicationId,
    required this.captureMethod,
    required this.cancellationReason,
    required this.canceledAt,
    required this.clientSecret,
    required this.confirmationMethod,
    required this.currency,
    required this.customerId,
    required this.descriptionX,
    required this.invoiceId,
    required this.onBehalfOf,
    required this.paymentMethodId,
    required this.reviewId,
    required this.receiptEmail,
    required this.setupFutureUsage,
    required this.transferGroup,
  });
}

/// The possible statuses for a [PaymentIntentApi].
///
/// https://stripe.com/docs/api/payment_intents/object#payment_intent_object-status
enum PaymentIntentStatusApi {
  /// The [PaymentIntentApi] was canceled.
  canceled,

  /// The [PaymentIntentApi] is in the middle of full EMV processing.
  processing,

  /// Next step: capture the [PaymentIntentApi] on your backend via the Stripe API.
  requiresCapture,

  /// Next step: process the payment by calling [Terminal.processPaymentIntent].
  requiresConfirmation,

  /// Next step: process the payment by calling [Terminal.processPaymentIntent].
  requiresPaymentMethod,

  /// Next step: the payment requires additional actions, such as authenticating with 3D Secure.
  ///
  /// PaymentIntents collected with the Terminal SDK should not end in the requires_action status.
  requiresAction,

  /// The [PaymentIntentApi] succeeded.
  succeeded,

  /// The [PaymentIntentApi] was authorized but its capture window lapsed, so it
  /// must be authorized again before it can be captured (extended/reauthorization).
  requiresReauthorization,
}

/// Contains details about items included in the [PaymentIntentApi] amount
class AmountDetailsApi {
  /// Details about the tip
  final TipApi? tip;

  const AmountDetailsApi({required this.tip});
}

// PARAMETERS

class PaymentIntentParametersApi {
  /// The amount of the payment, provided in the currency’s smallest unit.
  final int amount;

  /// Three-letter ISO currency code, in lowercase. Must be a supported currency.
  final String currency;

  /// The capture method that this PaymentIntent should use.
  final CaptureMethodApi captureMethod;

  /// The list of payment method types that this PaymentIntent is allowed to use.
  final List<PaymentMethodTypeApi> paymentMethodTypes;

  /// Set of key-value pairs that you can attach to an object. This can be useful for storing
  /// additional information about the object in a structured format.
  final Map<String, String> metadata;

  /// An arbitrary string attached to the object. If you send a receipt email for this payment,
  /// the email will include the description.
  final String? descriptionX;

  /// A string to be displayed on your customer’s credit card statement. This may be up to 22 characters.
  /// The statement descriptor must contain at least one letter, may not include <>"' characters,
  /// and will appear on your customer’s statement in capital letters. Non-ASCII characters
  /// are automatically stripped. While most banks and card issuers display this information consistently,
  /// some may display it incorrectly or not at all.
  final String? statementDescriptor;

  /// A string to specify details about the transaction so your customer can understand it clearly
  /// on their statement. The suffix is concatenated with the statementDescriptor, the * symbol,
  /// and a space to form the complete statement descriptor that your customer sees. Maximum 22
  /// characters for the final concatenated descriptor.
  final String? statementDescriptorSuffix;

  /// Email address that the receipt for the resulting payment will be sent to.
  final String? receiptEmail;

  /// The ID of the Customer this [PaymentIntentApi] is for, if one exists.
  final String? customerId;

  /// The amount of the application fee (if any) that will be applied to the payment and transferred
  /// to the application owner’s Stripe account. To use an application fee, the request must be made
  /// on behalf of another account, using the stripeAccount property or an OAuth key.
  final int? applicationFeeAmount;

  /// The account (if any) the payment will be attributed to for tax reporting, and where funds
  /// from the payment will be transferred to upon payment success.
  ///
  /// At capture time, use `transfer_data[amount]` to specify the amount that will be transferred
  /// automatically when a charge succeeds.
  ///
  /// When [transferDataDestination] is specified, [onBehalfOf] must also be specified and must
  /// match the destination of the transfer.
  final String? transferDataDestination;

  /// A string that identifies the resulting payment as part of a group.
  final String? transferGroup;

  /// The Stripe account ID for which these funds are intended.
  ///
  /// When [transferDataDestination] is specified, [onBehalfOf] must also be specified and
  /// must match the destination of the transfer.
  final String? onBehalfOf;

  /// Indicates that you intend to make future payments with this [PaymentIntentApi]’s payment method.
  ///
  /// Providing this parameter will attach the payment method to the [PaymentIntentApi]’s Customer,
  /// after the [PaymentIntentApi] is confirmed and any required actions from the user are complete.
  /// If no Customer was provided, the payment method can still be attached to a Customer after
  /// the transaction completes.
  final PaymentIntentUsageApi? setupFutureUsage;

  /// Specific options used during the creation of the PaymentMethod.
  final PaymentMethodOptionsParametersApi? paymentMethodOptionsParameters;

  PaymentIntentParametersApi({
    required this.amount,
    required this.currency,
    this.captureMethod = CaptureMethodApi.manual,
    this.paymentMethodTypes = const [PaymentMethodTypeApi.cardPresent],
    this.metadata = const {},
    this.descriptionX,
    this.statementDescriptor,
    this.statementDescriptorSuffix,
    this.receiptEmail,
    this.customerId,
    this.applicationFeeAmount,
    this.transferDataDestination,
    this.transferGroup,
    this.onBehalfOf,
    this.setupFutureUsage,
    this.paymentMethodOptionsParameters,
  });
}

/// Controls when the funds will be captured from the customer’s account.
enum CaptureMethodApi {
  /// Stripe automatically captures funds when the customer authorizes the payment.
  automatic,

  /// Place a hold on the funds when the customer authorizes the payment, but don’t capture
  /// the funds until later. Will require an explicit call to capture payments.
  /// (Not all payment methods support this.)
  manual,
}

enum ConfirmationMethodApi {
  /// After next_actions are handled, no additional confirmation is required to complete the payment.
  automatic,

  /// All payment attempts must be made using a secret key. The PaymentIntent returns to the
  /// requires_confirmation state after handling next_actions, and requires your server to
  /// initiate each payment attempt with an explicit confirmation.
  manual,
}

enum PaymentIntentUsageApi {
  /// Use “on_session” if you intend to only reuse the payment method when your customer
  /// is present in your checkout flow.
  onSession,

  /// Use “off_session” if your customer may or may not be present in your checkout flow.
  offSession,
}

/// The PaymentMethodOptionsParameters contains options for PaymentMethod creation.
class PaymentMethodOptionsParametersApi {
  /// Card-present-specific configuration for this PaymentMethod.
  final CardPresentParametersApi cardPresentParameters;

  const PaymentMethodOptionsParametersApi({required this.cardPresentParameters});
}

/// Configuration for confirming a payment intent.
class ConfirmPaymentIntentConfigurationApi {
  /// The URL to redirect the customer back to after authentication.
  final String? returnUrl;

  const ConfirmPaymentIntentConfigurationApi({this.returnUrl});
}
