name: shelf_open_api
description: Open api specs generators from dart code for shelf package.
repository: https://github.com/BreX900/mek-packages
issue_tracker: https://github.com/BreX900/mek-packages/issues
homepage: https://github.com/BreX900/mek-packages/tree/main/shelf_packages/shelf_open_api
version: 1.1.0

environment:
  sdk: ^3.8.0

dependencies:
  meta: ^1.9.0
#  shelf_routing: ^1.1.3

dev_dependencies:
  mek_lints: ^3.0.0

#dependency_overrides:
#  shelf_routing:
#    path: ../../mek-packages/shelf_packages/shelf_routing
