name: shelf_routing_generator
description: Generator for routing class methods with support for path parameters, query parameters, body and headers.
repository: https://github.com/BreX900/mek-packages
issue_tracker: https://github.com/BreX900/mek-packages/issues
homepage: https://github.com/BreX900/mek-packages/tree/main/shelf_packages/shelf_routing_generator
version: 2.0.0

environment:
  sdk: ^3.8.0

scripts:
  # To generate .g files:
  generate-code: dart run build_runner watch --delete-conflicting-outputs --verbose

  publish: dart pub publish

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_routing: ^1.0.0
  http_methods: ^1.1.0

  analyzer: '>=7.4.0 <9.0.0'
  build: '>=3.0.0 <5.0.0'
  source_gen: '>=3.1.0 <5.0.0'
  code_builder: ^4.4.0

  collection: ^1.19.1
  recase: ^4.1.0

dev_dependencies:
  mek_lints: ^4.0.0

  test: ^1.26.2
  mocktail: ^1.0.4
  build_test: ^3.3.2

  decimal: ^3.2.1
  build_runner: ^2.7.0

dependency_overrides:
  shelf_routing: { path: ../shelf_routing }
