name: shelf_routing_generator
description: Generator for routing class methods with support for path parameters, query parameters, body and headers.
repository: https://github.com/BreX900/mek-packages
issue_tracker: https://github.com/BreX900/mek-packages/issues
homepage: https://github.com/BreX900/mek-packages/tree/main/shelf_packages/shelf_routing_generator
version: 0.1.0

environment:
  sdk: '>=3.8.0 <4.0.0'

scripts:
  publish: dart pub publish
  generate-code: dart run build_runner watch --delete-conflicting-outputs --verbose

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_routing: ^0.1.0
  http_methods: ^1.0.0

  build: ^2.4.2
  source_gen: ^2.0.0
  analyzer: ^7.3.0
  dart_style: ^3.0.0
  code_builder: ^4.0.0

  collection: ^1.19.0
  recase: ^4.1.0
  glob: ^2.1.3
  path: ^1.9.1

dev_dependencies:
  mek_lints: ^4.0.0

  test: ^1.26.2
  mocktail: ^1.0.4
  build_test: ^2.2.3

  decimal: ^3.2.1
  build_runner: ^2.4.15

dependency_overrides:
  shelf_routing: { path: ../shelf_routing }
