name: Integration StripeTerminal

on:
  pull_request:
    paths: [ 'mek_stripe_terminal/**' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    defaults:
      run:
        working-directory: mek_stripe_terminal

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.47.x'

      - name: Resolve dependencies
        run: flutter pub get
        timeout-minutes: 2

      - name: Check code formatting
        run: >-
          dart format --set-exit-if-changed --output none
          $(find . ! -path "./.dart_tool/**" ! -path "./build/**" -name "*.dart" ! -name "*.g.dart")

      - name: Analyze code
        run: flutter analyze --no-fatal-infos
      
  integration-example:
    runs-on: macos-latest
    timeout-minutes: 5

    defaults:
      run:
        working-directory: mek_stripe_terminal/example

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.47.x'

      - name: Resolve dependencies
        run: flutter pub get
        timeout-minutes: 2

      - name: Check code formatting
        run: >-
          dart format --set-exit-if-changed --output none
          $(find . ! -path "./.dart_tool/**" ! -path "./build/**" -name "*.dart" ! -name "*.g.dart")

      - name: Analyze code
        run: flutter analyze --no-fatal-infos
